<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="3" time="0.237" timestamp="2021-06-23T14:54:00.490403" hostname="DESKTOP-IFANMFL"><testcase classname="test_pdemo" name="test_add" time="0.001" /><testcase classname="test_pdemo" name="test_answer" time="0.002"><failure message="assert 9 == 5&#10;  +9&#10;  -5">def test_answer():
    
&gt;       assert sub(10) == 5
E       assert 9 == 5
E         +9
E         -5

test_pdemo.py:14: AssertionError</failure></testcase><testcase classname="test_pdemo" name="test_add_2" time="0.001"><failure message="assert (5 * 5) &lt;= 10">def test_add_2():
        a = 5
        b = 5
&gt;       assert a * b &lt;= 10
E       assert (5 * 5) &lt;= 10

test_pdemo.py:19: AssertionError</failure></testcase></testsuite></testsuites>